### ISSUE TITLE
'GLIBC_2.34' not found

### ISSUE THREAD

**Issue by kennethrrosen** [mahancoder/Adobe-Connect-Linux#11]
**Describe the bug**
Application doesn't launch from menu or terminal or meeting link

**To Reproduce**
1. Click app icon, unresponsive
2. in terminal: xdg-open connectpro:https//google.com
3. ./connect: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found

**Expected behavior**
Opens application or opens browser

**Desktop (please complete the following information):**
 - Qubes 4.1.1

**Comment by mahanla** [comment]
Thanks for reporting, I'll make a new build today, fixing the issue

**Comment by mahanla** [comment]
@kennethrrosen Sorry for the delay, but your local GLIBC versions are different from my machine on which I do the builds. To fix the issue, build from the source on your machine
