### ISSUE TITLE
Screen share and share documents 

### ISSUE THREAD

**Issue by AliBaghdadii** [mahancoder/Adobe-Connect-Linux#12]
Hello, is there any way you share your screen and share documents? I need screen share for my work.

**Comment by mahanla** [comment]
As mentioned in the readme, the share screen feature does not work, because it relies on proprietary code that can't be easily reverse engineered. However, the document share _should_ work, but I haven't tested it myself

**Comment by ilia85-star** [comment]
It's a bit late but there is a good way. you can stream your screen to a virtual webcam (obs-studio has a tool called virtual camera for that) and use your webcam to share your screen.

**Comment by mahanla** [comment]
@ilia85-star Yes, I've personally been using this setup for a while now. However, considering the fact that you need to change the Webcam quality to HD for it to be even remotely usable, and also the inconsistency of this setup with certain compositor and display servers, I didn't include the solution in the readme. I guess I can point it out as an experimental solution though.
