### ISSUE TITLE
Cannot connect my voice

### ISSUE THREAD

**Issue by machitgarha** [mahancoder/Adobe-Connect-Linux#3]
**Describe the bug**

The microphone does not work. Adjusting the volume and changing the microphone source does not fix the problem. The voice icon, however, is shown as connected (i.e. green without a line over it), but no voice is recognized and transferred. Obviously, the waves next to the microphone icon appearing when you speak is not shown either.

Note that, the problem is not with the microphone or other components. Other applications are working well.

It might be related to PipeWire and the specific chromium version not supporting it, or even the Wireplumber server, but not totally sure.

**To Reproduce**

1. Open an online room.
1. Request voice permission, if not already granted (i.e. raise your hand).
1. Click on the microphone icon to enable your microphone.
1. Start speaking. 
1. No one can hear you.

**Expected behavior**

My voice must be enabled. 

**Desktop:**
 - Distro: Fedora Workstation 35
 - Version 35

**Additional context**

Gnome 41.3 on Wayland
Wireplumber 0.4.7
Pipewire 0.3.45

**Comment by mahancoder** [comment]
I've been using this app for a long time now, and haven't seen such an issue. You can check which source the app is recording using `pavucontrol` app. Check if everything is right, and if the issue persists, do the following.
Run the following command in the terminal
`xdg-open connectpro:https://mictests.com/`
Test the microphone and all the devices.
After the test is done, copy all the terminal outputs and post them here.

**Comment by machitgarha** [comment]
Here is the log:

[adobe-connect-linux.log](https://github.com/mahancoder/Adobe-Connect-Linux/files/8066968/adobe-connect-linux.log)

And here is the video of what I've done (the unnecessary part skipped):

[adobe-connect-linux.zip](https://github.com/mahancoder/Adobe-Connect-Linux/files/8067115/adobe-connect-linux.zip)

**Note:** Uploading the video as video failed, so I compressed and uploaded.

**Comment by mahancoder** [comment]
Thanks, I found the cause in your log file:
`"Microphone and Camera access no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS.`

Your meeting server should have HTTPS since I used a newer, more secure version of chromium and flash.
For security reasons, I won't downgrade the libraries to a lower version, so this issue will be closed.
